### ISSUE TITLE
No download info given for 'curl_proj' and its source directory

### ISSUE THREAD

**Issue by huy-lv** [meetecho/janus-mobile-sdk#6]
Hi, i have cloned your project and tried to run android example but got some errors:
`No download info given for 'curl_proj' and its source directory`

After a few minutes, i found `CMakeList.txt` file and I have tried to add `GIT_REPOSITORY ...` for `mbedtls_proj` and `json_proj` like this photo, but i cannot find the git repo for `curl_proj`

Could you tell me the correct url to make this work?

![image](https://user-images.githubusercontent.com/7688070/68868622-6dc6fe00-072a-11ea-8fe1-c171049e4e9a.png)

**Comment by helloIAmPau** [comment]
did you run `make` from the root folder of the project? 
from the readme:
>The make command downloads all the native dependencies you need to build the library on each platform. Once the make command finished, you are ready to link the platform-specific code to your iOS or Android project.

**Comment by huy-lv** [comment]
You said run `git clone https://github.com/helloiampau/janus-client` but this project seems not public.
Where should i run `make` command :(

**Comment by helloIAmPau** [comment]
That is the old URL of the repo, but all the commands are still valid. I'll update the readme with the new URL.

**Comment by huy-lv** [comment]
Thank you for updating new README, when i run `make` command from `janus-mobile-sdk` dir, it got an error, i'm using Window 10 with GNUWIN32 to run `make` command.
http://gnuwin32.sourceforge.net/packages/make.htm

![image](https://user-images.githubusercontent.com/7688070/68915066-38a2c600-0793-11ea-9df8-420eb8ac2164.png)

**Comment by helloIAmPau** [comment]
Windows is not 100% supported.
You can use "WSL 2" to run linux applications on your box: https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by huy-lv** [comment]
I tried on Mac and got this problem, please help me to run it, i already installed NDK, Cmake from Android studio SDK manager.
`fatal error: 'djinni_support.hpp' file not found`

![image](https://user-images.githubusercontent.com/7688070/68987974-9baf5e00-0862-11ea-9b2c-ef1204f77df2.png)

**Comment by helloIAmPau** [comment]
You right, I missed a dependency in my last commit. Please update to the master and check if it works. Thank you.

**Comment by huy-lv** [comment]
Thank you, the previous error gone but new one came :(
![image](https://user-images.githubusercontent.com/7688070/68994619-916b7f00-08b7-11ea-803f-fa5e8a820359.png)

**Comment by helloIAmPau** [comment]
That is because Android Studio didn't get that you've updated the files. Try to clean/update the project.

**Comment by borhanreo** [comment]
I face the same problem. even i run `make` successfully . could you help me please
